
### get all
GET https://cse341-xats.onrender.com/users


### get single 
Get https://cse341-xats.onrender.com/users/67cba5c88d16db7b01e7117e

### create new
POST https://cse341-xats.onrender.com/users
Content-Type: application/json

{
    "firstname": "Noah",
    "lastname": "Ruppe",
    "email": "noah.ruppe30@gmail.com",
    "favoritecolor": "Green",
    "birthday": "May 14, 1999"
}
### update
Put https://cse341-xats.onrender.com/users/67d2fb652f218e74c810fb2b
Content-Type: application/json

{
    "firstname": "Ray",
    "lastname": "Ruppe",
    "email": "ray2ruppe@yahoo.com",
    "favoritecolor": "Blue",
    "birthday": "May 5, 1973"
}


### delete
Delete https://cse341-xats.onrender.com/users/67d301ca84c35d58eebd0a73
